var d=self,k=d.Df;(function(){function a(a){c?c.push(a):setTimeout(a,0)}var b={version:"0.7.2.0",Hg:function(a){return void 0===a},Gg:function(a){return null===a},oa:function(a){return null===a||void 0===a},Ig:function(a){return null!==a&&void 0!==a}},c=[];d.attachEvent&&d.attachEvent("onload",function(){if(c){var a=c;c=null;for(var b=0,f=a.length;b<f;b++)a[b]()}});k||(d.Df=k={Oa:a,Rg:a});for(var f in b)k[f]=b[f]})();Object.$="Object";Object.Aa=null;Object.lg=function(a){for(var b in a)delete a[b]};
Object.Rd=function(a,b){return void 0!==a[b]};Object.keys?Object.tf=function(a){return Object.keys(a).length}:(Object.keys=function(a){var b=[],c;for(c in a)b.push(c);return b},Object.tf=function(a){var b=0,c;for(c in a)b++;return b});Boolean.$="Boolean";Boolean.parse=function(a){return"true"==a.toLowerCase()};Number.$="Number";
Number.parse=function(a){return a&&a.length?0<=a.indexOf(".")||0<=a.indexOf("e")||(1>a.length?0:"f"==a.substr(a.length-1))||(1>a.length?0:"F"==a.substr(a.length-1))?parseFloat(a):parseInt(a,10):0};Number.prototype.Ma=function(a){return k.oa(a)||0==a.length||"i"==a?this.toString():w(this,a,!1)};Number.prototype.Td=function(a){return k.oa(a)||0==a.length||"i"==a?this.toLocaleString():w(this,a,!0)};
Number.qc=function(a,b,c,f){var e=null;c=a.indexOf(c);0<c&&(e=a.substr(c),a=a.substr(0,c));(c=K(a,"-"))&&(a=a.substr(1));var g=0,l=b[g];if(a.length<l)return e?a+e:a;for(var m=a.length,h="",n=!1;!n;){var r=l,u=m-r;0>u&&(l+=u,r+=u,u=0,n=!0);if(!r)break;u=a.substr(u,r);h=h.length?u+f+h:u;m-=r;g<b.length-1&&(g++,l=b[g])}c&&(h="-"+h);return e?h+e:h};
function w(a,b,c){c=c?k.Zd.Nf.Af:k.Zd.Of.Af;var f="",e=-1;1<b.length&&(e=parseInt(b.substr(1)));b=b.charAt(0);switch(b){case "d":case "D":f=parseInt(Math.abs(a)).toString();-1!=e&&(f=O(f,e));0>a&&(f="-"+f);break;case "x":case "X":f=parseInt(Math.abs(a)).toString(16);"X"==b&&(f=f.toUpperCase());-1!=e&&(f=O(f,e));break;case "e":case "E":f=-1==e?a.toExponential():a.toExponential(e);"E"==b&&(f=f.toUpperCase());break;case "f":case "F":case "n":case "N":-1==e&&(e=c.Jg);f=a.toFixed(e).toString();e&&"."!=
c.Wd&&(e=f.indexOf("."),f=f.substr(0,e)+c.Wd+f.substr(e+1));if("n"==b||"N"==b)f=Number.qc(f,c.Lg,c.Wd,c.Kg);break;case "c":case "C":-1==e&&(e=c.pg);f=Math.abs(a).toFixed(e).toString();e&&"."!=c.Ld&&(e=f.indexOf("."),f=f.substr(0,e)+c.Ld+f.substr(e+1));f=Number.qc(f,c.rg,c.Ld,c.qg);f=0>a?String.Ma(c.sg,f):String.Ma(c.tg,f);break;case "p":case "P":-1==e&&(e=c.Mg),f=(100*Math.abs(a)).toFixed(e).toString(),e&&"."!=c.Xd&&(e=f.indexOf("."),f=f.substr(0,e)+c.Xd+f.substr(e+1)),f=Number.qc(f,c.Og,c.Xd,c.Ng),
f=0>a?String.Ma(c.Pg,f):String.Ma(c.Qg,f)}return f}String.$="String";String.$d="";String.nf=function(a,b,c){c&&(a&&(a=a.toUpperCase()),b&&(b=b.toUpperCase()));a=a||"";b=b||"";return a==b?0:a<b?-1:1};String.concat=function(){return 2===arguments.length?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,"")};String.vg=function(a,b,c){return 0==String.nf(a,b,c)};
String.hd=function(a,b,c){String.jd||(String.jd=/(\{[^\}^\{]+\})/g);return a.replace(String.jd,function(a,e){var g=b[parseInt(e.substr(1))+1];if(k.oa(g))return"";if(g.Ma){var l=null,m=e.indexOf(":");0<m&&(l=e.substring(m+1,e.length-1));return c?g.Td(l):g.Ma(l)}return c?g.toLocaleString():g.toString()})};String.Ma=function(a){return String.hd(a,arguments,!1)};String.qf=function(a,b){for(var c=a,f=1;f<b;f++)c+=a;return c};String.xf=function(a){return!a||!a.length};
String.Td=function(a){return String.hd(a,arguments,!0)};function O(a,b){return a.length<b?String.qf("0",b-a.length)+a:a}String.prototype.remove=function(a,b){return!b||a+b>this.length?this.substr(0,a):this.substr(0,a)+this.substr(a+b)};function K(a,b){return b.length?b.length>a.length?!1:a.substr(0,b.length)==b:!0}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/\s*$/,"").replace(/^\s*/,"")});Array.$="Array";Array.Jb=[k.Hb];Array.prototype.add=function(a){this.push(a)};
Array.prototype.Hc=function(){return 1===this.length?[this[0]]:Array.apply(null,this)};Array.prototype.contains=function(a){return 0<=this.indexOf(a)};function Q(a){return a.length?a[a.bg?0:a.length-1]:null}Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,f=0;f<c;f++)if(f in this&&!a.call(b,this[f],f,this))return!1;return!0});
Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,f=[],e=0;e<c;e++)if(e in this){var g=this[e];a.call(b,g,e,this)&&f.push(g)}return f});Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,f=0;f<c;f++)f in this&&a.call(b,this[f],f,this)});Array.prototype.Na=function(){return new k.Fb(this)};Array.prototype.index=function(a,b){for(var c=this.length,f={},e=0;e<c;e++)if(e in this){var g=a.call(b,this[e],e);String.xf(g)||(f[g]=this[e])}return f};
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length;if(c)for(var f=b||0;f<c;f++)if(this[f]===a)return f;return-1});Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,f=Array(c),e=0;e<c;e++)e in this&&(f[e]=a.call(b,this[e],e,this));return f});Array.parse=function(a){return eval("("+a+")")};Array.prototype.remove=function(a){a=this.indexOf(a);return 0<=a?(this.splice(a,1),!0):!1};Array.prototype.Jc=function(a){this.splice(a,1)};
Array.prototype.some||(Array.prototype.some=function(a,b){for(var c=this.length,f=0;f<c;f++)if(f in this&&a.call(b,this[f],f,this))return!0;return!1});Array.Ff=function(a){return Array.prototype.slice.call(a)};RegExp.$="RegExp";RegExp.parse=function(a){if(K(a,"/")){var b=a.lastIndexOf("/");if(1<b)return RegExp(a.substring(1,b),a.substr(b+1))}return null};Error.$="Error";
Error.ng=function(a,b,c){a=Error(a);if(b)for(var f in b)a[f]=b[f];c&&(a.zg=c);if(!(k.oa(a.stack)||k.oa(a.fileName)||k.oa(a.lineNumber))){b=a.stack.split("\n");c=b[0];for(f=a.fileName+":"+a.lineNumber;!k.oa(c)&&-1===c.indexOf(f);)b.shift(),c=b[0];c=b[1];isNullOrUndefined(c)||(c=c.match(/@(.*):(\d+)$/),k.oa(c)||(b.shift(),a.stack=b.join("\n"),a.fileName=c[1],a.lineNumber=parseInt(c[2])))}return a};k.ja=d.ja||function(){};k.ja.$="Debug";
k.ja.writeln||(k.ja.writeln=function(a){d.console?d.console.debug?d.console.debug(a):d.console.log&&d.console.log(a):d.opera&&d.opera.postError&&d.opera.postError(a)});k.ja.gd=function(a){k.ja.writeln(a);eval("debugger;")};k.ja.assert=function(a,b){a||(b="Assert failed: "+b,confirm(b+"\r\n\r\nBreak into debugger?")&&k.ja.gd(b))};k.ja.wg=function(a){k.ja.gd(a)};d.w=Function;d.w.$="Type";d.Sc=function(a){this.$=a};d.Sc.prototype={ke:!0};
d.w.Bf=function(){d.nc||(d.nc={});d.Wc||(d.Wc=[]);if(!d.nc.trn){for(var a=self,b=["trn"],c=0;c<b.length;c++){var f=b[c],e=a[f];e||(a[f]=e=new d.Sc(b.slice(0,c+1).join(".")),0==c&&d.Wc.add(e));a=e}d.nc.trn=a}};d.w.prototype.L=function(a,b,c){this.prototype.constructor=this;this.$=a;this.Tc=!0;this.Aa=b||Object;b&&(this.Ib=!0);if(c){this.Jb=[];for(var f=2;f<arguments.length;f++)c=arguments[f],this.Jb.add(c)}};function R(a,b){a.$=b;a.Vc=!0}
d.w.prototype.Kc=function(){if(this.Ib){var a=this.Aa;a.Ib&&a.Kc();for(var b in a.prototype){var c=a.prototype[b];this.prototype[b]||(this.prototype[b]=c)}delete this.Ib}};d.w.prototype.Cf||(d.w.prototype.Cf=d.w.prototype.Kc);function T(a,b){return k.oa(b)?!1:a==Object||b instanceof a?!0:U(a,d.w.sf(b))}
function U(a,b){if(a==Object||a==b)return!0;if(a.Tc)for(var c=b.Aa;c;){if(a==c)return!0;c=c.Aa}else if(a.Vc){var f=b.Jb;if(f&&f.contains(a))return!0;for(c=b.Aa;c;){if((f=c.Jb)&&f.contains(a))return!0;c=c.Aa}}return!1}d.w.Bg=function(a){return!0==a.Tc};d.w.Cg=function(a){return!0==a.je};d.w.Dg=function(a){return!0==a.je&&!0==a.Uc};d.w.Eg=function(a){return!0==a.Vc};d.w.Fg=function(a){return!0==a.ke};d.w.jg=function(a,b){return T(b,a)};d.w.Tg=function(a,b){return T(b,a)?a:null};
d.w.sf=function(a){var b=null;try{b=a.constructor}catch(c){}b&&b.$||(b=Object);return b};d.w.vf=function(a){if(!a)return null;d.w.oc||(d.w.oc={});var b=d.w.oc[a];b||(b=eval(a),d.w.oc[a]=b);return b};d.w.parse=function(a){return d.w.vf(a)};k.lc=function(){};k.lc.L("Enum");
k.lc.parse=function(a,b){var c=a.prototype;if(a.Uc){for(var f=b.split("|"),e=0,g=!0,l=f.length-1;0<=l;l--){var m=f[l].trim(),h=!1;for(n in c)if(n===m){e|=c[n];h=!0;break}if(!h){g=!1;break}}if(g)return e}else for(var n in c)if(n===b)return c[n];throw"Invalid Enumeration Value";};
k.lc.Tf=function(a){var b=this.prototype;if(this.Uc&&0!==a){var c=[];for(f in b)b[f]&a&&(c.length&&c.add(" | "),c.add(f));if(!c.length)throw"Invalid Enumeration Value";return c.join("")}for(var f in b)if(b[f]===a)return f;throw"Invalid Enumeration Value";};k.I=function(){};k.I.L("Delegate");k.I.empty=function(){};k.I.ne=function(a,b,c){for(var f=0;f<a.length;f+=2)if(a[f]===b&&a[f+1]===c)return!0;return!1};
k.I.rc=function(a){function b(){if(2==a.length)return a[1].apply(a[0],arguments);for(var c=a.Hc(),b=0;b<c.length;b+=2)k.I.ne(a,c[b],c[b+1])&&c[b+1].apply(c[b],arguments);return null}b.na=a;return b};k.I.create=function(a,b){return a?k.I.rc([a,b]):b};k.I.mg=function(a,b){return a?b?k.I.rc((a.na?a.na:[null,a]).concat(b.na?b.na:[null,b])):a.na?a:k.I.create(null,a):b.na?b:k.I.create(null,b)};
k.I.remove=function(a,b){if(!a||a===b)return null;if(!b)return a;var c=a.na,f=null,e;b.na?(f=b.na[0],e=b.na[1]):e=b;for(var g=0;g<c.length;g+=2)if(c[g]===f&&c[g+1]===e){if(2==c.length)return null;c.splice(g,2);return k.I.rc(c)}return a};k.I.og=function(a,b,c){c=c||"__"+(new Date).valueOf();self[c]=b?a:function(){try{delete self[c]}catch(b){self[c]=void 0}a.apply(null,arguments)};return c};k.I.ug=function(a){delete self[a]};k.I.kg=function(a){self[a]=k.I.empty};k.jb=function(){};k.jb.prototype={Ud:null};
k.jb.Na=function(a){return a?a.Na?a.Na():new k.Fb(a):null};R(k.jb,"IEnumerator");k.Hb=function(){};k.Hb.prototype={Na:null};R(k.Hb,"IEnumerable");k.Fb=function(a){this.Xc=a;this.Ea=-1;this.Md=null};k.Fb.prototype={Ud:function(){this.Ea++;this.Md=this.Xc[this.Ea];return this.Ea<this.Xc.length}};k.Fb.L("ArrayEnumerator",null,k.jb);k.Pc=function(){};k.Pc.prototype={pf:null};R(k.Pc,"IDisposable");k.Rc=function(a){this.af=k.oa(a)?[]:[a]};k.Rc.prototype={toString:function(a){return this.af.join(a||"")}};
k.Rc.L("StringBuilder");k.Gb=function(){};k.Gb.L("EventArgs");k.Gb.$d=new k.Gb;d.XMLHttpRequest||(d.XMLHttpRequest=function(){for(var a=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(c){}return null});k.Oc=function(){var a=k.Oc;a.Ib&&a.Kc();a.Aa.apply(this);this.cancel=!1};k.Oc.L("CancelEventArgs",k.Gb);k.he=function(){};k.he.L("Tuple");k.Z=function(){this.wb=null};k.Z.prototype={};k.Z.Ec=[];k.Z.Ye={pf:function(){k.Z.Ec.pop()}};
k.Z.Sg=function(a){k.Z.Ec.push(a);return k.Z.Ye};k.Z.le=function(a){var b=k.Z.Ec,c=b.length;if(c){a=a||[];for(var f=0;f<c;f++){var e=b[f];a.contains(e)||a.push(e)}return a}return null};k.Z.Re=function(a){for(var b=0,c=a.length;b<c;b++)a[b].Ag()};k.Z.L("Observable");k.Qc=function(a){this.Ga=a||[];this.wb=null};
k.Qc.prototype={add:function(a){this.Ga.push(a);V(this)},contains:function(a){return this.Ga.contains(a)},Na:function(){this.wb=k.Z.le(this.wb);return this.Ga.Na()},indexOf:function(a){return this.Ga.indexOf(a)},remove:function(a){return this.Ga.remove(a)?(V(this),!0):!1},Jc:function(a){this.Ga.Jc(a);V(this)},Ff:function(){return this.Ga}};function V(a){var b=a.wb;b&&(a.wb=null,k.Z.Re(b))}k.Qc.L("ObservableCollection",null,k.Hb);k.ae=function(){};R(k.ae,"IApplication");k.be=function(){};R(k.be,"IContainer");
k.ee=function(){};R(k.ee,"IObjectFactory");k.ce=function(){};R(k.ce,"IEventManager");k.de=function(){};R(k.de,"IInitializable");(function(a){function b(a,b,e,g,l,h){this.za=16;this.ge=288;this.status=0;this.root=null;this.qa=0;var m=Array(this.za+1),n,v,D,t,q,s,F,G=Array(this.za+1),C,B,A,y=new c,L=Array(this.za);t=Array(this.ge);var z,H=Array(this.za+1),I,J,M;M=this.root=null;for(q=0;q<m.length;q++)m[q]=0;for(q=0;q<G.length;q++)G[q]=0;for(q=0;q<L.length;q++)L[q]=null;for(q=0;q<t.length;q++)t[q]=0;for(q=0;q<H.length;q++)H[q]=0;n=256<b?a[256]:this.za;C=a;B=0;q=b;do m[C[B]]++,B++;while(0<--q);if(m[0]==b)this.root=null,this.status=
this.qa=0;else{for(s=1;s<=this.za&&0==m[s];s++);F=s;h<s&&(h=s);for(q=this.za;0!=q&&0==m[q];q--);D=q;h>q&&(h=q);for(I=1<<s;s<q;s++,I<<=1)if(0>(I-=m[s])){this.status=2;this.qa=h;return}if(0>(I-=m[q]))this.status=2,this.qa=h;else{m[q]+=I;H[1]=s=0;C=m;B=1;for(A=2;0<--q;)H[A++]=s+=C[B++];C=a;q=B=0;do 0!=(s=C[B++])&&(t[H[s]++]=q);while(++q<b);b=H[D];H[0]=q=0;C=t;B=0;t=-1;z=G[0]=0;A=null;for(J=0;F<=D;F++)for(a=m[F];0<a--;){for(;F>z+G[1+t];){z+=G[1+t];t++;J=(J=D-z)>h?h:J;if((v=1<<(s=F-z))>a+1)for(v-=a+1,
A=F;++s<J&&!((v<<=1)<=m[++A]);)v-=m[A];z+s>n&&z<n&&(s=n-z);J=1<<s;G[1+t]=s;A=Array(J);for(v=0;v<J;v++)A[v]=new c;M=null==M?this.root=new f:M.next=new f;M.next=null;M.list=A;L[t]=A;0<t&&(H[t]=q,y.ha=G[t],y.ea=16+s,y.Pa=A,s=(q&(1<<z)-1)>>z-G[t],L[t-1][s].ea=y.ea,L[t-1][s].ha=y.ha,L[t-1][s].pa=y.pa,L[t-1][s].Pa=y.Pa)}y.ha=F-z;B>=b?y.ea=99:C[B]<e?(y.ea=256>C[B]?16:15,y.pa=C[B++]):(y.ea=l[C[B]-e],y.pa=g[C[B++]-e]);v=1<<F-z;for(s=q>>z;s<J;s+=v)A[s].ea=y.ea,A[s].ha=y.ha,A[s].pa=y.pa,A[s].Pa=y.Pa;for(s=1<<
F-1;0!=(q&s);s>>=1)q^=s;for(q^=s;(q&(1<<z)-1)!=H[t];)z-=G[t],t--}this.qa=G[1];this.status=0!=I&&1!=D?1:0}}}function c(){this.pa=this.ha=this.ea=0;this.Pa=null}function f(){this.list=this.next=null}var e=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],g=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],l=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],m=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,
1537,2049,3073,4097,6145,8193,12289,16385,24577],h=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],n=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];a.Ta||(a.Ta={});a.Ta.mc=function(a){this.Lf();this.jc=a;this.kc=0};a.Ta.mc.prototype={Od:function(a){for(var c,b=Array(1024),f=[],e=0;e<a&&0<(c=this.Kf(b,0,b.length));)f[f.length]=String.fromCharCode.apply(null,b.slice(0,c)),e+=c;return e?(this.jc=this.jc.slice(this.kc),this.kc=0,f.join("")):""},Gf:function(){return this.jc.length==
this.kc?-1:this.jc.charCodeAt(this.kc++)&255},D:function(a){for(;this.Qa<a;)this.ib|=this.Gf()<<this.Qa,this.Qa+=8},H:function(a){return this.ib&e[a]},B:function(a){this.ib>>=a;this.Qa-=a},ic:function(a,c,b){var f,e,g;if(0==b)return 0;for(g=0;;){this.D(this.ia);e=this.ya.list[this.H(this.ia)];for(f=e.ea;16<f;){if(99==f)return-1;this.B(e.ha);f-=16;this.D(f);e=e.Pa[this.H(f)];f=e.ea}this.B(e.ha);if(16==f)this.S&=32767,a[c+g++]=this.xa[this.S++]=e.pa;else{if(15==f)break;this.D(f);this.Y=e.pa+this.H(f);
this.B(f);this.D(this.hb);e=this.Yd.list[this.H(this.hb)];for(f=e.ea;16<f;){if(99==f)return-1;this.B(e.ha);f-=16;this.D(f);e=e.Pa[this.H(f)];f=e.ea}this.B(e.ha);this.D(f);this.Ra=this.S-e.pa-this.H(f);for(this.B(f);0<this.Y&&g<b;)this.Y--,this.Ra&=32767,this.S&=32767,a[c+g++]=this.xa[this.S++]=this.xa[this.Ra++]}if(g==b)return b}this.wa=-1;return g},Mf:function(a,c,b){var f;f=this.Qa&7;this.B(f);this.D(16);f=this.H(16);this.B(16);this.D(16);if(f!=(~this.ib&65535))return-1;this.B(16);this.Y=f;for(f=
0;0<this.Y&&f<b;)this.Y--,this.S&=32767,this.D(8),a[c+f++]=this.xa[this.S++]=this.H(8),this.B(8);0==this.Y&&(this.wa=-1);return f},Jf:function(a,c,f){if(null==this.hc){var e,p=Array(288);for(e=0;144>e;e++)p[e]=8;for(;256>e;e++)p[e]=9;for(;280>e;e++)p[e]=7;for(;288>e;e++)p[e]=8;this.Nc=7;e=new b(p,288,257,g,l,this.Nc);if(0!=e.status)return alert("HufBuild error: "+e.status),-1;this.hc=e.root;this.Nc=e.qa;for(e=0;30>e;e++)p[e]=5;this.Mc=5;e=new b(p,30,0,m,h,this.Mc);if(1<e.status)return this.hc=null,
alert("HufBuild error: "+e.status),-1;this.Hf=e.root;this.Mc=e.qa}this.ya=this.hc;this.Yd=this.Hf;this.ia=this.Nc;this.hb=this.Mc;return this.ic(a,c,f)},If:function(a,c,f){var e,p,E,x,S,v,D,t=Array(316);for(e=0;e<t.length;e++)t[e]=0;this.D(5);v=257+this.H(5);this.B(5);this.D(5);D=1+this.H(5);this.B(5);this.D(4);e=4+this.H(4);this.B(4);if(286<v||30<D)return-1;for(p=0;p<e;p++)this.D(3),t[n[p]]=this.H(3),this.B(3);for(;19>p;p++)t[n[p]]=0;this.ia=7;p=new b(t,19,19,null,null,this.ia);if(0!=p.status)return-1;
this.ya=p.root;this.ia=p.qa;x=v+D;for(e=E=0;e<x;)if(this.D(this.ia),S=this.ya.list[this.H(this.ia)],p=S.ha,this.B(p),p=S.pa,16>p)t[e++]=E=p;else if(16==p){this.D(2);p=3+this.H(2);this.B(2);if(e+p>x)return-1;for(;0<p--;)t[e++]=E}else{17==p?(this.D(3),p=3+this.H(3),this.B(3)):(this.D(7),p=11+this.H(7),this.B(7));if(e+p>x)return-1;for(;0<p--;)t[e++]=0;E=0}this.ia=9;p=new b(t,v,257,g,l,this.ia);0==this.ia&&(p.status=1);if(0!=p.status)return-1;this.ya=p.root;this.ia=p.qa;for(e=0;e<D;e++)t[e]=t[e+v];this.hb=
6;p=new b(t,D,0,m,h,this.hb);this.Yd=p.root;this.hb=p.qa;return 0==this.hb&&257<v||0!=p.status?-1:this.ic(a,c,f)},Lf:function(){null==this.xa&&(this.xa=Array(65536));this.Qa=this.ib=this.S=0;this.wa=-1;this.gc=!1;this.Y=this.Ra=0;this.hc=this.ya=null},Kf:function(a,c,b){var e,f;for(e=0;e<b&&(!this.gc||-1!=this.wa);){if(0<this.Y){if(0!=this.wa)for(;0<this.Y&&e<b;)this.Y--,this.Ra&=32767,this.S&=32767,a[c+e++]=this.xa[this.S++]=this.xa[this.Ra++];else{for(;0<this.Y&&e<b;)this.Y--,this.S&=32767,this.D(8),
a[c+e++]=this.xa[this.S++]=this.H(8),this.B(8);0==this.Y&&(this.wa=-1)}if(e==b)break}if(-1==this.wa){if(this.gc)break;this.D(1);0!=this.H(1)&&(this.gc=!0);this.B(1);this.D(2);this.wa=this.H(2);this.B(2);this.ya=null;this.Y=0}switch(this.wa){case 0:f=this.Mf(a,c+e,b-e);break;case 1:f=null!=this.ya?this.ic(a,c+e,b-e):this.Jf(a,c+e,b-e);break;case 2:f=null!=this.ya?this.ic(a,c+e,b-e):this.If(a,c+e,b-e);break;default:f=-1}if(-1==f)return this.gc?0:-1;e+=f}return e}};a.Ta.yg=function(c){return(new a.Ta.mc(c)).Od(4E7)}})(self);(function(a){function b(a){this.depth=this.index=0;this.v=a;this.location={start:0,cc:1,dc:1,end:a.length,empty:!0};this.Db=[this.location];this.Ic=!1;"?"===this.v.charAt(1)&&this.Qd();this.location.empty=!1}b.prototype={advance:function(){this.va=null;this.Qd();var a=this.location.start;++a;this.location.empty=!1;if("/"!==this.v.charAt(a))return this.location.empty="/"===this.v.charAt(this.v.indexOf(">",a)-1),!0;this.location.end=!0;return!1},of:function(a){if(a)return a.split("&quot;").join('"').split("&lt;").join("<").split("&gt;").join(">").split("&amp;").join("&")},
Sd:function(){var a=this.location.start+1,b=this.v.indexOf(">",a);this.location.empty&&--b;a=this.v.substring(a,b);this.va={};b=a.indexOf(" ");if(-1!==b){this.Nd=a.substring(0,b);for(var a=a.slice(b),a=a.split('"'),b=a.length-1,e=0;e<b;++e){var g=a[e],l=a[++e];this.va[g.substring(1,g.length-1)]=l}}else this.Nd=a},Qd:function(){if(this.Ic)this.Ic=!1,this.location.start=this.v.indexOf("<",this.location.start+1);else{var a=this.location.cc;if(!this.location.empty)for(var b=this.location.dc;0<b;)a=this.v.indexOf("<",
a),"/"===this.v.charAt(++a)?--b:(a=this.v.indexOf(">",a),"/"!==this.v.charAt(a-1)&&++b);this.location.start=this.v.indexOf("<",a)}this.location.cc=this.location.start+1;this.location.dc=1},ec:function(){this.v.ec&&this.v.ec(this.location.start)},A:function(){null!==this.va&&"undefined"!==typeof this.va||this.Sd();return this.Nd},s:function(){++this.depth;this.location={start:this.location.start};this.Db[this.Db.length]=this.location;this.Ic=!0},q:function(){--this.depth;this.va=null;var a=this.location.cc,
b=this.location.dc,e=this.location.empty,g=this.location.end;this.Db.pop();this.location=this.Db[this.Db.length-1];this.location.cc=a;this.location.dc=g?0:e?b:b+1},G:function(){return this.location.empty?!0:"/"===this.v.charAt(this.v.indexOf("<",this.location.start+1)+1)},r:function(a){null!==this.va&&"undefined"!==typeof this.va||this.Sd();return this.of(this.va[a])}};a.ie=b})(self);d=self;self.w.Bf();
d.trn.a=function(a,b){this.bc=!1;this.xd=1E4;this.Ia={};this.La=this.vb=0;this.C=[];this.Tb=[];this.ca=[];this.ca.add({});this.ub=0;this.c=a;this.Bd=this.Eb("Width");this.Ad=this.Eb("Height");this.C.push(d.trn.Da.wf(this.Bd,this.Ad));this.R="c."+d.trn.a.d[d.trn.a.Ge]+"();";this.ma="c."+d.trn.a.d[d.trn.a.Fe]+"();";this.V=!1;this.wd=b;this.Se=-1<navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("Chrome")&&-1===navigator.userAgent.indexOf("Firefox");this.b="";this.c.s();this.c.advance();
var c=this.c.A();d.trn.a.g(c,"FixedPage.Resources")&&(this.c.s(),this.c.advance(),this.Gd(),this.c.q());this.Ha=!1};d.trn.a.g=function(a,b){var c=d.trn.a.mf;return a===b?!0:a===c+b};d.trn.a.i=function(a){return d.trn.a.zb(a,3)};d.trn.a.Ab=function(a){return a.split("\\").join("\\\\").split('"').join('\\"')};d.trn.a.zb=function(a,b){var c=b,f=Math.abs(a);0.5>f&&(c=5E-4>f?5E-7>f?b+6:b+4:b+2);c=Math.pow(10,c);a=Math.round(a*c)/c;return a.toString()};d.trn.a.n=function(a,b){if(!a)throw Error(b);};
d.trn.a.xg=function(a){return(new d.trn.a(a,!1)).Le()};
d.trn.a.prototype={ld:function(a){return a+"."+d.trn.a.d[d.trn.a.fd]+"(t.m_a,t.m_b,t.m_c,t.m_d,t.m_h,t.m_v);"},oe:function(a){var b="oc"+this.ta,c="ox"+this.ta;this.b+="var "+b+"=document.createElement('canvas');";this.b+=b+".width=b[2]";this.b+=";"+b+".height=b[3]";this.b+=";";this.b+="var "+c+"="+b+".getContext('2d');";b="o"+this.ta;this.b+="var "+b+"=function(c,ob){";this.b+="c."+d.trn.a.d[d.trn.a.$c]+"();";this.b+="c."+d.trn.a.d[d.trn.a.tc]+"(0,0);";this.b+="c."+d.trn.a.d[d.trn.a.lb]+"(b[2],0);";
this.b+="c."+d.trn.a.d[d.trn.a.lb]+"(b[2],b[3]);";this.b+="c."+d.trn.a.d[d.trn.a.lb]+"(0,b[3]);";this.b+="c."+d.trn.a.d[d.trn.a.ad]+"();";this.b+="c."+d.trn.a.d[d.trn.a.Nb]+"(-b[0],-b[1]);";this.b+=this.ld("c");var f=this.Ya(),e=this.c.r("RenderTransform");if(null!=e){var g=new d.trn.p;g.M(e);f.Ba(g)}this.b+=f.nb();this.b+=a;this.b+="};";this.b+=b+"("+c+",b);";return c},Oe:function(a){var b="t"+this.ta;this.b+=this.td("var "+b+"=function(c,ob)");var c="tx"+this.ta;this.b+=a+".width=b[2];";this.b+=
a+".height=b[3];";this.b+="var "+c+"="+a+".getContext('2d');";a=this.Ya();this.b+=c+"."+d.trn.a.d[d.trn.a.Nb]+"(-b[0],-b[1]);";this.b+=this.ld(c);this.b+=a.pd(c);this.b+=b+"("+c+",b);";return c},sc:function(a){var b,c=this.Ke(),f=this.c.A();d.trn.a.g(f,"Path")?b=this.xc():d.trn.a.g(f,"Canvas")?b=this.Ob():d.trn.a.g(f,"Glyphs")?b=this.wc():(b=null,d.trn.a.n(!1,"Invalid Element "+f));b.fb(c);if(b.yf()){var c="m"+ ++this.ta,f="d"+this.ta,e="tc"+this.ta;this.b+="var b=["+d.trn.a.i(b.k)+","+d.trn.a.i(b.l)+
","+d.trn.a.i(b.k+b.u)+","+d.trn.a.i(b.l+b.t)+"];";this.b+="var x1=b[0]*t.m_a + b[1]*t.m_c + t.m_h;";this.b+="var y1=b[0]*t.m_b + b[1]*t.m_d + t.m_v;";this.b+="var x2=b[2]*t.m_a + b[3]*t.m_c + t.m_h;";this.b+="var y2=b[2]*t.m_b + b[3]*t.m_d + t.m_v;";this.b+="if(x1<x2){b[0]=Math.floor(x1);b[2]=Math.ceil(x2-x1);}else{b[2]=Math.ceil(x1-x2);b[0]=Math.floor(x2);}";this.b+="if(y1<y2){b[1]=Math.floor(y1);b[3]=Math.ceil(y2-y1);}else{b[3]=Math.ceil(y1-y2);b[1]=Math.floor(y2);}";this.b+="var "+e+"=document.createElement('canvas');";
b=this.Oe(e);a=this.oe(a);this.b+="var "+c+"="+a+"."+d.trn.a.d[d.trn.a.cd]+"(0,0,b[2],b[3]);";this.b+="var "+f+"="+b+"."+d.trn.a.d[d.trn.a.cd]+"(0,0,b[2],b[3]);";this.b+="var m = b[3]*b[2]<<2;";this.b+="for(var s=3;s<m;s+=4){";this.b+=f+".data[s]*=";this.b+=c+".data[s]/255;";this.b+="}";this.b+=b+"."+d.trn.a.d[d.trn.a.De]+"("+f+",0,0);";this.b+=this.R;this.b+="c."+d.trn.a.d[d.trn.a.He]+"(1,0,0,1,b[0]-ob[0],b[1]-ob[1]);";this.b+="c."+d.trn.a.d[d.trn.a.Lb]+"("+e+",0,0);";this.b+=this.ma}else this.V=
!1},Ob:function(){var a=new d.trn.T;this.K();var b=this.c.r("RenderTransform");if(null!=b){var c=new d.trn.p;c.M(b);this.J(c)}b=this.c.r("Clip");null!=b&&(a=this.sa(b));b=null;if(!this.c.G()){for(this.c.s();this.c.advance();)c=this.c.A(),d.trn.a.g(c,"Canvas.Clip")?(d.trn.a.n(!this.c.G(),"Canvas.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(c=new d.trn.p,c.M(this.m("Transform")),this.J(c),a.fb(this.sa(this.m("Figures"))),c=c.pb(),this.J(c)),this.c.q()):d.trn.a.g(c,"Path")?
null!=b?b.Lc(this.xc()):b=this.xc():d.trn.a.g(c,"Glyphs")?null!=b?b.Lc(this.wc()):b=this.wc():d.trn.a.g(c,"Canvas")&&(null!=b?b.Lc(this.Ob()):b=this.Ob());this.c.q()}null!=b&&a.fb(b);this.da();return a},bf:function(){var a=this.Fc();a||(this.b+=this.R,this.K());var b=null,c=this.c.r("OpacityMask");null!=c&&(b=this.Xa(c,!0,"c."+d.trn.a.d[d.trn.a.Va]+"();"));if(!this.c.G()){for(this.c.s();this.c.advance();)if(c=this.c.A(),d.trn.a.g(c,"Canvas.Resources"))this.c.G()?d.trn.a.n(!1,"Canvas.Resources must contain ResourceDictionary element"):
(this.c.s(),this.c.advance(),this.Gd(),this.c.q());else if(d.trn.a.g(c,"Canvas.Clip"))d.trn.a.n(!this.c.G(),"Canvas.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(a||(this.b+=this.R,a=!0,this.K()),c=new d.trn.p,c.M(this.m("Transform")),this.b+=this.J(c),d.trn.a.n(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),this.$b(this.m("Figures")),c=c.pb(),this.b+=this.J(c)),this.c.q();else if(d.trn.a.g(c,"Canvas.OpacityMask"))this.V?this.V=!1:(this.c.s(),
this.c.advance(),b=this.Wa("c."+d.trn.a.d[d.trn.a.ka],"c."+d.trn.a.d[d.trn.a.Va]+"();"),this.c.q(),this.V=!0);else if(d.trn.a.g(c,"Path")||d.trn.a.g(c,"Glyphs")||d.trn.a.g(c,"Canvas")||d.trn.a.g(c,"trn:Glyphs")){if(null!=b){this.xb();this.c.q();this.V=!0;this.sc(b);return}this.Ha=!1;break}this.Ha&&this.c.q()}this.Ha&&this.xb()},xb:function(){this.b+=this.ma;this.da()},Eb:function(a){a=this.c.r(a);d.trn.a.n(null!=a,this.c.A()+": "+a+" is not defined");return parseFloat(a)},ra:function(a,b){a=this.c.r(a);
return null!=a?parseFloat(a):b},m:function(a){a=this.c.r(a);d.trn.a.n(null!=a,this.c.A()+": "+a+" is not defined");return a},gb:function(a,b){a=this.c.r(a);return null!=a?a:b},Pd:function(){var a;a=this.c.r("x:Key");d.trn.a.n(null!=a,"Key must be defined for elements in a resource dictionary");return a},Fc:function(){0===this.La&&this.c.ec();var a=!1,b=this.ra("Opacity",1);1>b&&(a||(a=!0,this.b+=this.R,this.K()),this.b+=this.Ua(b));b=this.c.r("RenderTransform");null!=b&&(a||(a=!0,this.b+=this.R,this.K()),
this.Fa(b)?this.b+=this.Qb(b):this.Ed(b));b=this.c.r("Clip");null!=b&&(a||(this.b+=this.R,this.K()),this.$b(b),a=!0);return a},$b:function(a){var b=!0;a&&"F"===a[0]&&(b=!1);this.Hd(b?"evenodd":"nonzero");this.Qe(this.sa(a));this.Gc(a);this.b+="c."+d.trn.a.d[d.trn.a.re]+"("+(b?"'evenodd'":"")+");"},$e:function(a){var b=[];for(a=k.jb.Na(a.split(";"));a.Ud();){var c=a.Md,f=new d.trn.Ea,c=c.split(",");if(1<=c.length){if(0<c[0].length){var e=c[0].split(")");if(2<=e.length){var g=e[0].substr(1).split(":");
f.zc=parseInt(g[0]);f.Ac=parseInt(g[1])}f.Wb=parseInt(e[e.length-1]);f.Yb=!0}2<=c.length&&(0<c[1].length&&(f.yc=parseFloat(c[1]),f.Cc=!0),3<=c.length&&(0<c[2].length&&(f.Xb=parseFloat(c[2])),4<=c.length&&0<c[3].length&&(f.Zb=parseFloat(c[3]))))}b.add(f)}return b},Pe:function(){var a=this.m("UnicodeString"),b="",c=0,f=0,e=0,g=0;for(2<=a.length&&"{"===a.charAt(0)&&"}"===a.charAt(1)&&(a=a.substr(2));c<a.length;)f=a.charCodeAt(c),9==f?(b+=String.fromCharCode(10),c++):128>f?(b+=String.fromCharCode(f),
c++):191<f&&224>f?(e=a.charCodeAt(c+1),b+=String.fromCharCode((f&31)<<6|e&63),c+=2):(e=a.charCodeAt(c+1),g=a.charCodeAt(c+2),b+=String.fromCharCode((f&15)<<12|(e&63)<<6|g&63),c+=3);return b},wc:function(){var a=new d.trn.T,b=this.c.r("Clip");null!=b&&(a=this.sa(b));return a},vc:function(a,b){return this.Se&&1===a.length?b[d.trn.a.xe]+'("'+(a+" "):b[d.trn.a.we]+'("'+a},Dd:function(a,b){var c=this.Fc(),f=this.Eb("OriginX"),e=this.Eb("OriginY"),g=this.m("FontUri");this.rb[g]=null;var l=this.Eb("FontRenderingEmSize"),
m=this.$e(this.gb("Indices",""));if(200>l){l/=200;c||(this.K(),this.b+=this.R,c=!0);var h=new d.trn.p;h.ob(l,0,0,l,f,e);l=200;f=e=0;this.b+=h.nb()}for(var h=0,n="p"+ ++this.Te,f="var "+n+"="+f+";",r=this.Pe(),u=0,P=0,N=l/100,p="",E=0;E<m.length;++E){var x=m[E];if(u!==x.Xb||P!==x.Zb)p&&(f+="c."+this.vc(d.trn.a.Ab(p),a)+'",'+n+(u?"+"+d.trn.a.i(u*N):"")+","+d.trn.a.i(e-P*N)+");",f+=n+"+=c."+a[d.trn.a.ed]+'("'+d.trn.a.Ab(p)+'").'+a[d.trn.a.Ie]+";"),u=x.Xb,P=x.Zb,p="";x.Cc?(f+="c."+this.vc(d.trn.a.Ab(p+
(x.Yb?String.fromCharCode(x.Wb+57344):r.substr(h,1))),a)+'",'+n+(u?"+"+d.trn.a.i(u*N):"")+","+d.trn.a.i(e-P*N)+");",f+=n+"+=",p&&(f+="c."+a[d.trn.a.ed]+'("'+d.trn.a.Ab(p)+'").width+'),f+=d.trn.a.i(x.yc*N)+";",p=""):p+=x.Yb?String.fromCharCode(x.Wb+57344):r.substr(h,1);E+=x.Ac-1;h+=x.zc}if(p||h<r.length)f+="c."+this.vc(d.trn.a.Ab(p+r.substr(h,r.length-h)),a)+'",'+n+","+d.trn.a.i(e)+");";m=e=null;h=this.c.r("OpacityMask");null!=h&&(m=this.Xa(h,!0,"c."+a[d.trn.a.Va]+"();"));if(!this.c.G()&&!b){for(this.c.s();this.c.advance();)h=
this.c.A(),d.trn.a.g(h,"Glyphs.Clip")?(d.trn.a.n(!this.c.G(),"Canvas.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(c||(c=!0,this.b+=this.R,this.K()),h=new d.trn.p,h.M(this.m("Transform")),this.b+=h.nb(),d.trn.a.n(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),n=this.m("Figures"),this.$b(n),h=h.pb(),this.b+=h.nb()),this.c.q()):d.trn.a.g(h,"Glyphs.Fill")?(this.c.s(),this.c.advance(),e=this.Wa("c."+a[d.trn.a.ka],f),this.c.q()):d.trn.a.g(h,"Glyphs.OpacityMask")&&
(this.V?this.V=!1:(this.c.s(),this.c.advance(),m=this.Wa("c."+a[d.trn.a.ka],"c."+a[d.trn.a.Va]+"();"),this.c.q(),this.V=!0));this.c.q()}null==m&&("otf"===g.substr(g.indexOf(".")+1)?(g=g.substr(0,g.length-4),g=parseInt(g.substr(7))):g=parseInt(g.substr(35,8),16),g="f"+g,Object.Rd(this.Ia,g)?10>this.Ia[g].length&&(this.Ia[g]+=r.substr(0,10-this.Ia[g].length)):this.Ia[g]=r.substr(0,10),this.ff(d.trn.a.i(l)+"px "+g),h=this.c.r("Fill"),null!=h&&(e=this.Fa(h)?this.Xa(h,!0,f):this.Rb(h,"c."+a[d.trn.a.ka],
f)),null!=e&&(-1===e.indexOf(this.R)?this.ac(e,f):this.ac("c."+a[d.trn.a.ka]+"='#000000';"+f,f)));c&&(this.b+=this.ma,this.da());null!=m&&(this.V=!0,this.sc(m))},md:function(){var a=new String;this.c.s();d.trn.a.n(this.c.advance(),"Gradient brushes must contain GradientStops");for(this.c.s();this.c.advance();)var b=this.m("Color"),c=this.m("Offset"),a=a+("g."+d.trn.a.d[d.trn.a.pe]+"("+c+","+this.kd(b)+");");this.c.q();this.c.q();return a},od:function(a,b,c){var f=this.c.r("Transform"),e=new String,
e=e+this.R;this.K();null!=f&&(c.M(f),e+=this.J(c));c=this.ra("Opacity",1);1>c&&(e+=this.Ua(c));c=this.m("StartPoint");f=this.m("EndPoint");e+="var g=c."+d.trn.a.d[d.trn.a.se]+"("+c+","+f+");";e+=this.md();e=e+(a+"=g;")+b;e+=this.ma;this.da();return e},qd:function(a,b,c){var f=this.c.r("Transform"),e=new String,g=this.m("RadiusX"),l=this.m("RadiusY"),m=this.m("GradientOrigin"),h=this.m("Center"),e=e+this.R;this.K();if(null!=f||g!==l)null!=f&&c.M(f),g!==l&&(f=parseFloat(g),l=parseFloat(l),d.trn.a.n(0<
f&&0<l,"Invalid radius value"),l/=f,f=new d.trn.p,f.ob(1,0,0,l,0,0),c.Ba(f),h=h.split(","),h=d.trn.a.i(parseFloat(h[0]))+","+d.trn.a.i(parseFloat(h[1])/l),m=m.split(","),m=d.trn.a.i(parseFloat(m[0]))+","+d.trn.a.i(parseFloat(m[1])/l)),e+=this.J(c);c=this.ra("Opacity",1);1>c&&(e+=this.Ua(c));e+="var g=c."+d.trn.a.d[d.trn.a.te]+"("+m+",0,"+h+","+g+");";e+=this.md();e=e+(a+"=g;")+b;e+=this.ma;this.da();return e},lf:function(){d.trn.a.n(!this.Vb,"Incorrect custom glyph start");this.b+="c."+d.trn.a.d[d.trn.a.ue]+
"();";this.Vb=!0},Je:function(){d.trn.a.n(this.Vb,"Incorrect custom glyph end");this.b+="c."+d.trn.a.d[d.trn.a.ve]+"();";this.Vb=!1},kf:function(a){var b=Q(this.C);a!==b.eb?(K(a,"c."+d.trn.a.d[d.trn.a.Mb]+"='")&&(b.eb=a),this.b+=a):this.b+="c."+d.trn.a.d[d.trn.a.mb]+"();"},ac:function(a,b){var c=Q(this.C);a!==c.$a?(K(a,"c."+d.trn.a.d[d.trn.a.ka]+"='")&&(c.$a=a),this.b+=a):this.b+=b},Ua:function(a){var b=Q(this.C);b.Ja*=a;a=""+("c."+d.trn.a.d[d.trn.a.ze]+"=");a+=d.trn.a.i(b.Ja);return a+";"},Hd:function(a){var b=
Q(this.C);a!==b.Za&&(b.Za=a,this.b+='c.mozFillRule="'+a+'";')},Id:function(a){var b=Q(this.C);a!==b.bb&&(b.bb=a,this.b+="c."+d.trn.a.d[d.trn.a.dd]+"=",this.b+=d.trn.a.i(a),this.b+=";")},gf:function(a){var b=Q(this.C);a!==b.ab&&(b.ab=a,this.b+="c."+d.trn.a.d[d.trn.a.Ae]+"='",this.b+=a,this.b+="';")},hf:function(a){var b=Q(this.C);a!==b.Ka&&(b.Ka=a,this.b+="c."+d.trn.a.d[d.trn.a.Be]+"='",this.b+=a,this.b+="';")},jf:function(a){var b=Q(this.C);a!==b.cb&&(b.cb=a,this.b+="c."+d.trn.a.d[d.trn.a.Ce]+"=",
this.b+=d.trn.a.i(a),this.b+=";")},ff:function(a){var b=Q(this.C);a!==b.tb&&(b.Ka=a,this.b+="c."+d.trn.a.d[d.trn.a.ye]+"='",this.b+=a,this.b+="';")},J:function(a){Q(this.C).la.Ba(a);return a.nb()},Ya:function(){return Q(this.C).la},Ke:function(){return Q(this.C).fa},Qe:function(a){Q(this.C).fa.fb(a)},K:function(a){a=a?Q(this.C).zf():Q(this.C).Hc();this.C.push(a);this.ca.add({})},da:function(){this.C.pop();this.ca.Jc(this.ca.length-1)},nd:function(a,b,c){var f="",e=this.c.r("Transform"),f=f+this.R;
this.K();var g=this.m("Viewbox"),l=new d.trn.T;l.Oa(g);var g=this.m("Viewport"),m=new d.trn.T;m.Oa(g);if(null!=e||l!==m){var g=m.u/l.u,h=m.t/l.t,n=m.k-l.k*g,l=m.l-l.l*h;null!=e&&(this.Fa(e)?f+=this.Qb(e):c.M(e));e=new d.trn.p;e.ob(g,0,0,h,n,l);c.Ba(e);f+=this.J(c)}c=this.ra("Opacity",1);1>c&&(f+=this.Ua(c));c=this.gb("TileMode","None");e=this.m("ImageSource");this.rb[e]=null;e="i"+parseInt(e.split("/")[2]);f=f+a+("=c."+d.trn.a.d[d.trn.a.bd]+"(window.ci."+e+",");f="None"===c?f+"'no-repeat'":f+"'repeat'";
f+=");";f+=b;f+=this.ma;this.da();return f},Me:function(){var a="",b=this.c.r("Transform"),a=a+this.R;this.K();var c=this.m("Viewbox"),f=new d.trn.T;f.Oa(c);var c=this.m("Viewport"),e=new d.trn.T;e.Oa(c);if(null!=b||f!==e){var c=e.u/f.u,g=e.t/f.t,l=e.k-f.k*c,f=e.l-f.l*g,e=new d.trn.p;null!=b&&(this.Fa(b)?a+=this.Qb(b):e.M(b));b=new d.trn.p;b.ob(c,0,0,g,l,f);e.Ba(b);a+=this.J(e)}b=this.ra("Opacity",1);1>b&&(a+=this.Ua(b));this.gb("TileMode","None");b=this.m("ImageSource");this.rb[b]=null;b="i"+parseInt(b.split("/")[2]);
this.wd?(a=a+("var img=window.ci."+b+";")+("var a=asc(t)*"+this.Ya().Bb()+";"),a+="var st=Math.log(1/a)*1.4;",a+="var sc=1;",a+="for(var i=1; i<st; ++i){",a+='var can=document.createElement("canvas");',a+="can.width = img.width * 0.5;",a+="can.height = img.height * 0.5;",a+='can.getContext("2d").'+d.trn.a.d[d.trn.a.Lb]+"(img, 0, 0, can.width, can.height);",a+="img=can;sc*=2;",a+="}",a+="c."+d.trn.a.d[d.trn.a.uc]+"(sc,sc);",a+="c."+d.trn.a.d[d.trn.a.Lb]+"(img, 0, 0);"):a+="c."+d.trn.a.d[d.trn.a.Lb]+
"(window.ci."+b+", 0, 0);";a+=this.ma;this.da();return a},df:function(){this.Ed(this.c.r("Matrix"))},Ed:function(a){if(null!=a){var b=new d.trn.p;b.M(a);this.b+=this.J(b)}},h:function(a){for(var b=new String;","!==a.o.charAt(a.j)&&" "!==a.o.charAt(a.j)&&"\x00"!==a.o.charAt(a.j)&&("E"===a.o.charAt(a.j)||"e"===a.o.charAt(a.j)||!("A"<=a.o.charAt(a.j)&&"Z">=a.o.charAt(a.j)||"a"<=a.o.charAt(a.j)&&"z">=a.o.charAt(a.j)));)b+=a.o.charAt(a.j),++a.j;for(;" "===a.o.charAt(a.j)||","===a.o.charAt(a.j);)++a.j;
return parseFloat(b)},sa:function(a){var b=" ",c=new d.trn.Kb(a,0,null,0),f=new d.trn.T,e=!0;f.Cb(0,0,0,0);if(c.j<c.o.length)for(;" "===c.o.charAt(c.j);)c.j++;for(;c.j<a.length;){if("A"<=c.o.charAt(c.j)&&"Z">=c.o.charAt(c.j)||"a"<=c.o.charAt(c.j)&&"z">=c.o.charAt(c.j))b=c.o.charAt(c.j),c.j++;else{var g,l;"a">b&&("H"!==b&&(c.f=0),"V"!==b&&(c.e=0));switch(b){case "m":case "M":c.e+=this.h(c);c.f+=this.h(c);e?(f.Cb(c.e,c.f,c.e,c.f),e=!1):f.X(c.e,c.f);c.F=!1;break;case "l":case "L":c.e+=this.h(c);c.f+=
this.h(c);f.X(c.e,c.f);c.F=!1;break;case "c":case "C":g=this.h(c)+c.e;l=this.h(c)+c.f;f.X(g,l);c.F=!0;c.aa=this.h(c)+c.e;c.ba=this.h(c)+c.f;f.X(c.aa,c.ba);c.e+=this.h(c);c.f+=this.h(c);f.X(c.e,c.f);break;case "q":case "Q":g=this.h(c)+c.e;l=this.h(c)+c.f;f.X(g,l);c.e+=this.h(c);c.f+=this.h(c);f.X(c.e,c.f);c.F=!1;break;case "s":case "S":c.F||(c.aa=c.e,c.ba=c.f);g=2*c.e-c.aa;l=2*c.f-c.ba;f.X(g,l);c.F=!0;c.aa=this.h(c)+c.e;c.ba=this.h(c)+c.f;f.X(c.aa,c.ba);c.e+=this.h(c);c.f+=this.h(c);f.X(c.e,c.f);break;
case "h":case "H":c.e+=this.h(c);f.X(c.e,c.f);c.F=!1;break;case "v":case "V":c.f+=this.h(c);f.X(c.e,c.f);c.F=!1;break;default:this.h(c),c.F=!1}}for(;" "===a.charAt(c.j);)++c.j}return f.uf(this.Ya())},xc:function(){var a=null;this.K();var b=this.c.r("RenderTransform");if(null!=b){var c=new d.trn.p;c.M(b);this.J(c)}b=this.c.r("Clip");null!=b&&(a=this.sa(b));b=this.c.r("Data");if(!this.c.G()){for(this.c.s();this.c.advance();)if(c=this.c.A(),d.trn.a.g(c,"Path.Data")&&!this.c.G()){this.c.s();this.c.advance()&&
(c=new d.trn.p,c.M(this.m("Transform")),this.J(c),d.trn.a.n(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Data must contain PathGeometry"),b=this.m("Figures"));this.c.q();break}else d.trn.a.g(c,"Path.Clip")&&(d.trn.a.n(!this.c.G(),"Path.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(c=new d.trn.p,c.M(this.m("Transform")),this.J(c),a=this.sa(this.m("Figures")),c=c.pb(),this.J(c)),this.c.q());this.c.q()}null!=a?a.fb(this.sa(b)):a=this.sa(b);this.da();return a},qb:function(a,b,
c){a.F=!1;if(null==a.ga)this.b+="c."+d.trn.a.d[d.trn.a.lb]+"("+d.trn.a.i(a.e)+","+d.trn.a.i(a.f)+");";else for(var f=a.ga.length,e=a.e-b,g=a.f-c,l=g/e,m=Math.sqrt(e*e+g*g);1E-10<m;){var h=a.ga[a.Ub%f]-a.sb,n=h>m;n&&(a.sb+=m,h=m);if(e){var r=Math.sqrt(h*h/(1+l*l));0>e&&(r=-r);b+=r;c+=l*r}else c+=0<g?h:-h;this.b+="c."+(a.Ub%2?d.trn.a.d[d.trn.a.tc]:d.trn.a.d[d.trn.a.lb])+"("+d.trn.a.i(b)+","+d.trn.a.i(c)+");";m-=h;n||(++a.Ub,a.sb=0)}},Zc:function(a,b,c,f,e){a.F=!0;if(null==a.ga)this.b+="c."+d.trn.a.d[d.trn.a.qe]+
"("+d.trn.a.i(f)+","+d.trn.a.i(e)+","+d.trn.a.i(a.aa)+","+d.trn.a.i(a.ba)+","+d.trn.a.i(a.e)+","+d.trn.a.i(a.f)+");";else{var g=this.Ya().Bb(),g=(Math.abs(a.e-b)+Math.abs(a.f-c))/5*g,l=a.e,m=a.f;a.e=b;a.f=c;for(var g=1/parseInt(g),h=0;1>=h;h+=g){var n=1-h,r=a.e,u=a.f;a.e=n*n*n*b+3*n*n*h*f+3*n*h*h*a.aa+h*h*h*l;a.f=n*n*n*c+3*n*n*h*e+3*n*h*h*a.ba+h*h*h*m;this.qb(a,r,u)}}},me:function(a){if(null==a.ga)this.b+="c."+d.trn.a.d[d.trn.a.ad]+"();";else{var b=a.e,c=a.f;a.e=a.yd;a.f=a.zd;this.qb(a,b,c)}},Xe:function(a){a.yd=
a.e;a.zd=a.f;this.b+="c."+d.trn.a.d[d.trn.a.tc]+"("+d.trn.a.i(a.e)+","+d.trn.a.i(a.f)+");";a.F=!1;a.Ub=a.Bc;a.sb=a.ua},cf:function(a,b){var c,f,e=a.e,g=a.f;"a">b&&("H"!==b&&(a.f=0),"V"!==b&&(a.e=0));switch(b){case "m":case "M":a.e+=this.h(a);a.f+=this.h(a);this.Xe(a);break;case "l":case "L":a.e+=this.h(a);a.f+=this.h(a);this.qb(a,e,g);break;case "c":case "C":c=this.h(a)+a.e;f=this.h(a)+a.f;a.aa=this.h(a)+a.e;a.ba=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.Zc(a,e,g,c,f);break;case "q":case "Q":c=
this.h(a)+a.e;f=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.b+="c."+d.trn.a.d[d.trn.a.Ee]+"("+d.trn.a.i(c)+","+d.trn.a.i(f)+","+d.trn.a.i(a.e)+","+d.trn.a.i(a.f)+");";a.F=!1;break;case "s":case "S":a.F||(a.aa=a.e,a.ba=a.f);c=2*a.e-a.aa;f=2*a.f-a.ba;a.F=!0;a.aa=this.h(a)+a.e;a.ba=this.h(a)+a.f;a.e+=this.h(a);a.f+=this.h(a);this.Zc(a,e,g,c,f);break;case "h":case "H":a.e+=this.h(a);this.qb(a,e,g);a.F=!1;break;case "v":case "V":a.f+=this.h(a);this.qb(a,e,g);a.F=!1;break;default:this.h(a),a.F=!1}},
Ne:function(a){if("Flat"===a)return"butt";if("Square"===a)return"square";if("Round"===a||"Triangle"===a)return"round";d.trn.a.n(!1,"Invalid line cap "+a);return""},Gc:function(a){this.Fd(a,null,0)},Fd:function(a,b,c){var f=" ";b=new d.trn.Kb(a,0,b,c);this.b+="c."+d.trn.a.d[d.trn.a.$c]+"();";if(b.j<b.o.length)for(;" "===b.o.charAt(b.j);)b.j++;for(;b.j<a.length;)for("A"<=b.o.charAt(b.j)&&"Z">=b.o.charAt(b.j)||"a"<=b.o.charAt(b.j)&&"z">=b.o.charAt(b.j)?(f=b.o.charAt(b.j),"z"!==b.o.charAt(b.j)&&"Z"!==
b.o.charAt(b.j)||this.me(b),b.j++):this.cf(b,f);" "===a.charAt(b.j);)++b.j},ef:function(){var a=this.c.r("Data"),b=!0;a&&"F"===a[0]&&(b=!1);var c="c."+d.trn.a.d[d.trn.a.Va]+"("+(b?"'evenodd'":"")+");",f=!1,e=this.Fc(),g=this.c.r("Fill");null!=g&&(g=this.Fa(g)?this.Xa(g,!0,c):this.Rb(g,"c."+d.trn.a.d[d.trn.a.ka],c));var l=null,m=0,m=this.ra("StrokeThickness",1),h=this.c.r("Stroke");null!=h&&(this.Id(m),h=this.Fa(h)?this.Xa(h,!1,"c."+d.trn.a.d[d.trn.a.mb]+"();"):this.Rb(h,"c."+d.trn.a.d[d.trn.a.Mb],
"c."+d.trn.a.d[d.trn.a.mb]+"();"));var n=null,r=this.c.r("OpacityMask");null!=r&&(n=this.Xa(r,!0,"c."+d.trn.a.d[d.trn.a.Va]+"();"));r=null;if(!this.c.G()){for(this.c.s();this.c.advance();){var u=this.c.A();d.trn.a.g(u,"Path.Clip")?(d.trn.a.n(!this.c.G(),"Path.Clip: Must contain PathGeometry element"),this.c.s(),this.c.advance()&&(e||(e=!0,this.b+=this.R,this.K()),r=new d.trn.p,r.M(this.m("Transform")),this.b+=this.J(r),d.trn.a.n(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Clip must contain PathGeometry"),
u=this.m("Figures"),this.$b(u),r=r.pb()),this.c.q()):d.trn.a.g(u,"Path.Data")&&!this.c.G()?(this.c.s(),this.c.advance()&&(a=new d.trn.p,a.M(this.m("Transform")),null!=r?r.Ba(a):r=a,this.b+=this.J(r),d.trn.a.n(d.trn.a.g(this.c.A(),"PathGeometry"),"Path.Data must contain PathGeometry"),a=this.m("Figures")),this.c.q()):d.trn.a.g(u,"Path.Fill")?(this.c.s(),this.c.advance(),null==n&&"ImageBrush"===this.c.A()&&(f=!0,this.b+=this.Me()),g=this.Wa("c."+d.trn.a.d[d.trn.a.ka],c),this.c.q()):d.trn.a.g(u,"Path.OpacityMask")?
this.V?this.V=!1:(this.c.s(),this.c.advance(),n=this.Wa("c."+d.trn.a.d[d.trn.a.ka],c),this.c.q(),this.V=!0):d.trn.a.g(u,"Path.Stroke")&&(this.c.s(),this.c.advance(),h=this.Wa("c."+d.trn.a.d[d.trn.a.Mb],"c."+d.trn.a.d[d.trn.a.mb]+"();",m),this.c.q())}this.c.q()}if(null==n&&!f){d.trn.a.n(null!=a,"Paths must have Data defined");f=this.c.r("StrokeDashArray");if(null!=f)for(f=f.split(" "),l=Array(f.length),r=0;r<f.length;++r)l[r]=parseFloat(f[r])*m,l[r]||(l[r]=0.005);this.Hd(b?"evenodd":"nonzero");m=this.ra("StrokeDashOffset",
0);null!=l&&null!=g&&(this.Gc(a),null!=g&&this.ac(g,c),g=null);this.Fd(a,l,m);null!=g&&this.ac(g,c);null!=h&&(this.gf(this.Ne(this.gb("StrokeStartLineCap","Flat"))),this.hf(this.gb("StrokeLineJoin","miter").toLowerCase()),this.jf(this.ra("StrokeMiterLimit",10)),this.kf(h))}e&&(this.b+=this.ma,this.da());null!=n&&(this.V=!0,this.sc(n))},kd:function(a){var b=1,c=[255,255,255,255];if("#"===a.charAt(0)){if(7===a.length)return"'"+a+"'";var b="FF",f,e;d.trn.a.n(9===a.length,"Color "+a+" is invalid in a XOD file");
b=a.substr(1,2);f=a.substr(3,2);e=a.substr(5,2);a=a.substr(7,2);b=parseInt(b,16)/255;c[0]=parseInt(f,16);c[1]=parseInt(e,16);c[2]=parseInt(a,16)}else"s"===a.charAt(0)?(f=a.split("#")[1].split(","),3<f.length?(b=parseFloat(f[0]),e=255*parseFloat(f[1]),c[0]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(f[2]),e=0>e?0:255<e?255:e,c[1]=parseInt(e),e=255*parseFloat(f[3])):(e=255*parseFloat(f[0]),e=0>e?0:255<e?255:e,c[0]=parseInt(e),e=255*parseFloat(f[1]),e=0>e?0:255<e?255:e,c[1]=parseInt(e),e=255*parseFloat(f[2])),
e=0>e?0:255<e?255:e,c[2]=parseInt(e)):d.trn.a.n(!1,"Invalid color for a XOD file");return"'rgba("+c[0]+","+c[1]+","+c[2]+","+d.trn.a.i(b)+")'"},rd:function(a,b){return this.Rb(this.m("Color"),a,b)},Rb:function(a,b,c){return b+"="+this.kd(a)+";"+c},Sb:function(a){return this.td("var "+a+"=function(c)")},td:function(a){this.Ha=!1;var b=this.La,c=this.b;this.b="";this.La=this.c.depth;this.K(!0);this.b+=a+"{";if(!this.c.G())for(;this.Dc(););this.da();this.b+="};";this.La=b;a=this.b;this.b=c;return a},
sd:function(a,b,c,f){var e="",g=this.m("Viewbox"),l=new d.trn.T;l.Oa(g);var g=this.m("Viewport"),m=new d.trn.T;m.Oa(g);g=this.c.r("Transform");e+=this.R;this.K();var h;if(!this.c.G()){for(this.c.s();this.c.advance();){var n=this.c.A();d.trn.a.g(n,"VisualBrush.Visual")&&(this.c.s(),d.trn.a.n(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),this.K(!0),Q(this.C).la=new d.trn.p,h=this.Ob(),this.da(),this.c.q())}this.c.q()}if("undefined"!==typeof h){var n=m.k-l.k,r=m.l-
l.l;l.fb(h);m=l;m.k+=n;m.l+=r}if(null!=g||l!==m)n=m.u/l.u,h=m.t/l.t,r=m.k-l.k*n,m=m.l-l.l*h,null!=g&&(this.Fa(g)?e+=this.Qb(g):c.M(g)),g=new d.trn.p,g.ob(n,0,0,h,r,m),c.Ba(g),e+=this.J(c);m=this.Ya().Bb();g=Math.min(l.u,l.t);e+="var a=asc(t)*"+d.trn.a.i(m)+";if(a*"+g+"<2)a=2/"+g+";";if(l.k||l.l)e+="c."+d.trn.a.d[d.trn.a.Nb]+"("+d.trn.a.i(l.k)+","+d.trn.a.i(l.l)+");";e+="c."+d.trn.a.d[d.trn.a.uc]+"(1/a,1/a);";m=this.ra("Opacity",1);1>m&&(e+=this.Ua(m));m=this.gb("TileMode","None");++this.vb;g="c"+
this.vb;h="x"+this.vb;e=e+("var "+g+"=document.createElement('canvas');")+(g+".width=");e+=l.u;e+="*a;"+g+".height=";e+=l.t;e+="*a;";e+="var "+h+"="+g+".getContext('2d');";e+=h+"."+d.trn.a.d[d.trn.a.uc]+"(a,a);";if(l.k||l.l)e+=h+"."+d.trn.a.d[d.trn.a.Nb]+"("+d.trn.a.i(-l.k)+","+d.trn.a.i(-l.l)+");";-1!==b.indexOf("c."+d.trn.a.d[d.trn.a.mb])&&(e+="c."+d.trn.a.d[d.trn.a.dd]+"=a*"+f/c.Bb()+";");c=this.c.r("Visual");c=null!=c?this.pc(c):"v"+this.vb;if(!this.c.G()){for(this.c.s();this.c.advance();)n=this.c.A(),
d.trn.a.g(n,"VisualBrush.Visual")&&(this.c.s(),d.trn.a.n(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),e+=this.Sb(c),this.c.q());this.c.q()}e+=c;e+="("+h+");";e+=a;e+="=c."+d.trn.a.d[d.trn.a.bd]+"("+g+",";e="None"===m?e+"'no-repeat'":e+"'repeat'";e+=");";e+=b;e+=this.ma;this.da();return e},Fa:function(a){return"{"===a.charAt(0)},pc:function(a){var b=a.indexOf("StaticResource");d.trn.a.n(0<b,"Invalid resource reference: "+a);b+=15;a=a.substr(b,a.length-1-b);for(var b=
null,c=this.ca.length-1;0<=c;--c)if(Object.Rd(this.ca[c],a)){b=this.ca[c][a];break}d.trn.a.n(null!=b,"Dictionary key "+a+" does not exist.");return b},Xa:function(a,b,c){return this.pc(a)+"(c,"+b+",'"+c+"');"},Qb:function(a){return this.pc(a)+"(c);"},Dc:function(){var a=!0;if(this.Ha){if(this.c.depth===this.La)return d.trn.a.g(this.c.A(),"Canvas")&&this.xb(),!1;a=this.c.advance();if(!a){this.c.q();if(Q(this.Tb)===this.c.depth)return this.Tb.pop(),this.Je(),!0;if(this.c.depth===this.La)return d.trn.a.g(this.c.A(),
"Canvas")&&this.xb(),!1;this.xb();return!0}}this.Ha=!0;a=this.c.A();d.trn.a.g(a,"Canvas")?this.bf():d.trn.a.g(a,"Path")?this.ef():d.trn.a.g(a,"Glyphs")?this.Dd(d.trn.a.d,!1):d.trn.a.g(a,"trn:Glyphs")&&(this.c.G()||this.Tb.push(this.c.depth),this.Dd(d.trn.a.Ze,!0),this.c.G()||(this.c.s(),this.lf()));return!0},Pb:function(){var a=this.Pd(),b="r"+this.ub.toString();++this.ub;return this.ca[this.ca.length-1][a]=b},Yc:function(){var a=this.Pb();this.b+="var "+a+"=function(c){\n"},kb:function(){var a=this.Pd(),
b="r"+this.ub.toString();++this.ub;this.ca[this.ca.length-1][a]=b;this.b+="var "+b+"=function(c,s,o){"},Ca:function(){this.b+="};"},Wa:function(a,b,c){var f=new d.trn.p,e=this.c.A();d.trn.a.g(e,"VisualBrush")?a=this.sd(a,b,f,c):(d.trn.a.g(e,"ImageBrush")?a=this.nd(a,b,f):d.trn.a.g(e,"LinearGradientBrush")?a=this.od(a,b,f):d.trn.a.g(e,"RadialGradientBrush")?a=this.qd(a,b,f):d.trn.a.g(e,"SolidColorBrush")?a=this.rd(a,b):(d.trn.a.n(!1,"Invalid Brush Type: "+e),a=""),"undefined"!==typeof c&&this.Id(c/
f.Bb()));return a},Gd:function(){var a=this.c.A();if(d.trn.a.g(a,"ResourceDictionary")&&!this.c.G()){var b="c[(s?'"+d.trn.a.d[d.trn.a.ka]+"':'"+d.trn.a.d[d.trn.a.Mb]+"')]";for(this.c.s();this.c.advance();)a=this.c.A(),d.trn.a.g(a,"ImageBrush")?(this.kb(),this.b+=this.nd(b,"eval(o);",new d.trn.p),this.Ca()):d.trn.a.g(a,"LinearGradientBrush")?(this.kb(),this.b+=this.od(b,"eval(o);",new d.trn.p),this.Ca()):d.trn.a.g(a,"RadialGradientBrush")?(this.kb(),this.b+=this.qd(b,"eval(o);",new d.trn.p),this.Ca()):
d.trn.a.g(a,"VisualBrush")?(this.kb(),this.b+=this.sd(b,"eval(o);",new d.trn.p),this.Ca()):d.trn.a.g(a,"SolidColorBrush")?(this.kb(),this.b+=this.rd(b,"eval(o);"),this.Ca()):d.trn.a.g(a,"MatrixTransform")?(this.Yc(),this.df(),this.Ca()):d.trn.a.g(a,"PathGeometry")?(this.Yc(),this.Gc(this.m("Figures")),this.Ca()):d.trn.a.g(a,"Path")?(a=this.Pb(),this.b+=this.Sb(a)):d.trn.a.g(a,"Glyphs")?(a=this.Pb(),this.b+=this.Sb(a)):d.trn.a.g(a,"Canvas")?(a=this.Pb(),this.b+=this.Sb(a)):d.trn.a.n(!1,"Resource type is invalid: "+
a);this.c.q()}},Le:function(){for(var a="";!this.bc;)a+=this.Vd();return a},Vd:function(){this.b+="var ob=[0,0];";for(this.rb={};this.b.length<this.xd&&this.Dc(););this.Dc()||(this.bc=!0);var a=this.b;this.b="";return a},rf:function(){var a=[],b=this.rb,c;for(c in b)a.add(c.substr(1));return a},bc:!1,Ha:!1,R:null,ma:null,V:!1,b:null,Bd:0,Ad:0,ub:0,vb:0,wd:!1,ta:0,Te:0,xd:0,Ia:null,rb:null,La:0,ca:null,C:null,c:null,Tb:null,Vb:!1};
d.trn.Ea=function(){this.Cc=this.Yb=!1;this.zc=this.Ac=1;this.yc=this.Xb=this.Zb=this.Wb=0};d.trn.Ea.prototype={Yb:!1,Cc:!1,zc:0,Ac:0,Wb:0,yc:0,Xb:0,Zb:0};d.trn.Da=function(){};d.trn.Da.wf=function(a,b){var c=new d.trn.Da;c.eb="black";c.$a="black";c.Za="nonzero";c.Ja=1;c.bb=1;c.ab="butt";c.Ka="miter";c.cb=10;c.tb="10px sans-serif";c.la=new d.trn.p;c.fa=new d.trn.T;c.fa.Cb(0,0,a,b);return c};
d.trn.Da.prototype={Hc:function(){var a=new d.trn.Da;a.eb=this.eb;a.$a=this.$a;a.Za=this.Za;a.Ja=this.Ja;a.bb=this.bb;a.ab=this.ab;a.Ka=this.Ka;a.cb=this.cb;a.tb=this.tb;a.la=new d.trn.p;a.la.ud(this.la);a.fa=new d.trn.T;a.fa.Cb(this.fa.k,this.fa.l,this.fa.u,this.fa.t);return a},zf:function(){var a=new d.trn.Da;a.eb="black";a.$a="black";a.Za="nonzero";a.Ja=1;a.bb=1;a.ab="butt";a.Ka="miter";a.cb=10;a.tb="10px sans-serif";a.la=new d.trn.p;a.la.ud(this.la);a.fa=new d.trn.T;return a},eb:null,$a:null,
Za:null,Ja:0,bb:0,ab:null,Ka:null,cb:0,tb:null,la:null,fa:null};d.trn.Sa=function(a,b){this.x=a;this.y=b};d.trn.Sa.prototype={x:0,y:0};d.trn.T=function(){this.l=this.k=-1E6;this.u=this.t=2E6};
d.trn.T.prototype={Cb:function(a,b,c,f){this.k=a;this.l=b;this.u=c;this.t=f},yf:function(){return 0<this.u&&0<this.t},Oa:function(a){a=a.split(",");d.trn.a.n(4===a.length,"Rectangles should contain 4 numbers");this.k=parseFloat(a[0]);this.l=parseFloat(a[1]);this.u=parseFloat(a[2]);this.t=parseFloat(a[3])},uf:function(a){if(a.vd())return this;var b=new d.trn.Sa(this.k,this.l),c=new d.trn.Sa(this.k,this.l+this.t),f=new d.trn.Sa(this.k+this.u,this.l),e=new d.trn.Sa(this.k+this.u,this.l+this.t);a.fc(b);
a.fc(c);a.fc(f);a.fc(e);a=Math.min(b.x,c.x,f.x,e.x);var g=Math.max(b.x,c.x,f.x,e.x),l=Math.min(b.y,c.y,f.y,e.y),b=Math.max(b.y,c.y,f.y,e.y),c=new d.trn.T;c.Cb(a,l,g-a,b-l);return c},X:function(a,b){a<this.k?(this.u+=this.k-a,this.k=a):a>this.k+this.u&&(this.u=a-this.k);b<this.l?(this.t+=this.l-b,this.l=b):b>this.l+this.t&&(this.t=b-this.l)},Lc:function(a){this.X(a.k,a.l);this.X(a.k+a.u,a.l+a.t)},fb:function(a){var b,c,f,e,g,l,m;b=this.k;c=this.k+this.u;f=this.l;e=this.l+this.t;g=a.k;l=a.k+a.u;m=a.l;
a=a.l+a.t;c<g||l<b||e<m||a<f?this.k=this.u=this.l=this.t=0:(this.k=b<g?g:b,this.u=(c<l?c:l)-this.k,this.l=f<m?m:f,this.t=(e<a?e:a)-this.l,this.u&&this.t||(this.k=this.u=this.l=this.t=0))},k:0,l:0,u:0,t:0};d.trn.p=function(){};
d.trn.p.prototype={N:1,O:0,P:0,Q:1,U:0,W:0,M:function(a){var b=[1,0,0,1,0,0];a=a.split(",");for(var c=0;c<a.length&&6>c;++c)b[c]=parseFloat(a[c]);this.N=b[0];this.O=b[1];this.P=b[2];this.Q=b[3];this.U=b[4];this.W=b[5]},ob:function(a,b,c,f,e,g){this.N=a;this.O=b;this.P=c;this.Q=f;this.U=e;this.W=g},ud:function(a){this.N=a.N;this.O=a.O;this.P=a.P;this.Q=a.Q;this.U=a.U;this.W=a.W},Ba:function(a){var b=this.N,c=this.O,f=this.P,e=this.Q;this.N=a.N*b+a.O*f;this.O=a.N*c+a.O*e;this.P=a.P*b+a.Q*f;this.Q=a.P*
c+a.Q*e;this.U=a.U*b+a.W*f+this.U;this.W=a.U*c+a.W*e+this.W},pb:function(){var a=new d.trn.p,b=this.N*this.Q-this.O*this.P;if(!b)return a;a.N=this.Q/b;a.P=-this.P/b;a.U=(this.P*this.W-this.U*this.Q)/b;a.O=-this.O/b;a.Q=this.N/b;a.W=-(this.N*this.W-this.U*this.O)/b;return a},fc:function(a){var b=a.x*this.O+a.y*this.Q+this.W;a.x=a.x*this.N+a.y*this.P+this.U;a.y=b},Bb:function(){var a=0.707106781*this.N+0.707106781*this.O,b=0.707106781*this.P+0.707106781*this.Q;return Math.sqrt(a*a+b*b)},vd:function(){return 1!==
this.N||this.O||this.P||1!==this.Q||this.U||this.W?!1:!0},nb:function(){return this.pd("c")},pd:function(a){return this.vd()?"":a+"."+d.trn.a.d[d.trn.a.fd]+"("+d.trn.a.zb(this.N,4)+","+d.trn.a.zb(this.O,4)+","+d.trn.a.zb(this.P,4)+","+d.trn.a.zb(this.Q,4)+","+d.trn.a.i(this.U)+","+d.trn.a.i(this.W)+");"}};
d.trn.Kb=function(a,b,c,f){this.o=a;this.j=b;this.e=this.f=0;this.F=!1;this.ga=c;if(null!=this.ga){for(b=a=0;b<this.ga.length;++b)a+=this.ga[b];this.ua=f%a;0>this.ua&&(this.ua+=a);for(b=this.Bc=0;this.ua>this.ga[b];++b)this.ua-=this.ga[b],++this.Bc}};d.trn.Kb.prototype={o:null,j:0,ga:null,Ub:0,sb:0,Bc:0,ua:0,e:0,f:0,yd:0,zd:0,F:!1,aa:0,ba:0};d.trn.Cd=function(a,b,c){this.Ve=a;this.We=b;this.Ue=c};d.trn.Cd.prototype={Ue:0,We:0,Ve:0};d.trn.a.L("myglobs.trn.Converter");d.trn.Ea.L("myglobs.trn._index");
d.trn.Da.L("myglobs.trn._gState");d.trn.Sa.L("myglobs.trn.Point");d.trn.T.L("myglobs.trn._rect");d.trn.p.L("myglobs.trn._matrix2D");d.trn.Kb.L("myglobs.trn._abbrGeomItr");d.trn.Cd.L("myglobs.trn._pageInfo");d.trn.a.Uf="http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key";d.trn.a.Yf="http://schemas.openxps.org/oxps/v1.0/resourcedictionary-key";d.trn.a.eg="http://schemas.microsoft.com/winfx/2006/xaml";d.trn.a.mf="http://schemas.microsoft.com/xps/2005/06";d.trn.a.fg="http://schemas.microsoft.com/winfx/2006/xaml/presentation";
d.trn.a.Zf="http://schemas.openxps.org/oxps/v1.0";d.trn.a.hg="http://schemas.microsoft.com/xps/2005/06/documentstructure";d.trn.a.Xf="http://schemas.openxps.org/oxps/v1.0/documentstructure";d.trn.a.cg="http://schemas.openxmlformats.org/package/2006/relationships";d.trn.a.Pf="http://schemas.openxmlformats.org/package/2006/content-types";d.trn.a.Vf="http://schemas.openxmlformats.org/markup-compatibility/2006";d.trn.a.Qf="http://schemas.openxmlformats.org/package/2006/metadata/core-properties";
d.trn.a.Rf="http://purl.org/dc/elements/1.1/";d.trn.a.Sf="http://purl.org/dc/terms/";d.trn.a.gg="http://www.w3.org/XML/1998/namespace";d.trn.a.dg="clr-namespace:PDFTron.SilverDox.Internal;assembly=SilverDox";d.trn.a.ig="http://schemas.microsoft.com/xps/2005/06/restricted-font";d.trn.a.$f="http://schemas.openxps.org/oxps/v1.0/restricted-font";d.trn.a.Wf="application/vnd.ms-package.obfuscated-opentype";d.trn.a.ag="http://www.pdftron.com/silverdox/2010/09";d.trn.a.Ge=0;d.trn.a.Fe=1;d.trn.a.fd=2;
d.trn.a.Nb=3;d.trn.a.dd=4;d.trn.a.Ae=5;d.trn.a.Mb=6;d.trn.a.ka=7;d.trn.a.ze=8;d.trn.a.se=9;d.trn.a.te=10;d.trn.a.bd=11;d.trn.a.pe=12;d.trn.a.$c=13;d.trn.a.ad=14;d.trn.a.Va=15;d.trn.a.mb=16;d.trn.a.re=17;d.trn.a.tc=18;d.trn.a.lb=19;d.trn.a.Ee=20;d.trn.a.qe=21;d.trn.a.ye=22;d.trn.a.we=23;d.trn.a.ed=24;d.trn.a.Ie=25;d.trn.a.Ce=26;d.trn.a.Be=27;d.trn.a.Lb=28;d.trn.a.He=29;d.trn.a.cd=30;d.trn.a.De=31;d.trn.a.uc=32;d.trn.a.xe=33;d.trn.a.ue=34;d.trn.a.ve=35;d.trn.a.d="S r t T w c s f a L R P A b z F X C M l q B n x m W i j I Z d D e xw cgb cge".split(" ");
d.trn.a.Ze="S r t T w c s f a L R P A b z F X C M l q B n xc m W i j I Z d D e xcw cgb cge".split(" ");self.trn.a||(self.trn=trn);function W(a){this.v="";this.Ef=new self.Ta.mc(a);X(this);this.start=0}W.prototype={Kd:102400,ec:function(a){var b=a-this.start;b>W.prototype.Kd&&(this.v=this.v.slice(b),this.start=a)},indexOf:function(a,b){var c;b-=this.start;do c=this.v.indexOf(a,b);while(-1===c&&X(this));return c+this.start},charAt:function(a){a-=this.start;a>=this.v.length&&X(this);return this.v.charAt(a)},substring:function(a,b){a-=this.start;b-=this.start;return this.v.substring(a,b)}};
function X(a){var b=a.Ef.Od(W.prototype.Kd);return b.length?(a.v+=b,!0):!1}self.fe=W;self.Jd=!1;
self.onmessage=function(a){switch(a.data.command){case "data":a=new self.ie(new self.fe(a.data.dataString));self.yb=new self.trn.a(a,self.Jd);break;case "nextChunk":self.yb.bc?(self.postMessage({command:"done"}),self.yb=null):(a=self.yb.Vd(),self.postMessage({command:"nextChunk",resources:self.yb.rf(),dataString:a}));break;case "cancel":self.yb=null;self.postMessage({command:"done"});break;case "options":self.Jd=a.data.imageScaling;break;default:throw Error("Unknown message command "+a.data.command);
}};
